### ISSUE TITLE
Instance: Fish samples; Matthew Kolmann

### ISSUE THREAD

**Issue by mkolmann** [MorphoCloud/MorphoCloudInstances#39]
### Cloud Computing Instance Flavor

g3.xl - GPU instance (32 CPUs, 125 GB RAM and A100 GPU)

### Description

trial 

### ORCID

0000-0001-9748-2066

### Email

U2FsdGVkX19f+Yj6AVagPuY0egUip228H6DGZkWuWcdwX/T1WRWvIWEwa990T4cJ

**Comment by muratmaga** [comment]
Dear MorphoCloud User,

We want to inform you that the current MorphoCloudInstances production service will be suspended on **June 1, 2026**. After that date, instances on the current platform will no longer be accessible.

We expect the new replacement platform to be operational by **July 1, 2026**, and potentially as early as before that date.

This transition is a hard reset:
- No instances, data, settings, or configurations from the current platform will be migrated.
- All users will need to onboard again when the new platform becomes available.

We understand this is a significant change. This reset is necessary to provide a stronger long-term foundation with:
- More flexibility in how you manage your instances
- Greater user control
- Improved privacy protections

The new platform will continue to run on GitHub and use the same control commands you already use. The key change is that we are moving to a GitHub organization model, and repositories will be accessible only to users who are members of the MorphoCloud organization.

If you would like to familiarize yourself in advance, draft onboarding instructions (subject to change) are available at https://github.com/MorphoCloud/docs. We will announce enrollment availability on the SlicerMorph/MorphoCloud mailing list. If you are not on that mailing list, please sign up at http://bit.ly/SM-listserv.

**Comment by muratmaga** [comment]
**📢 Important update for MorphoCloud users**

This notice is being posted on all open and closed issues to make sure prior users are aware of upcoming changes to the MorphoCloud Instances infrastructure. The changes bring easier access and management, more privacy, as well as new features such as using the infrastructure in the classroom.

**Sunset of the current system**

Starting **June 1st**, the existing repository (https://github.com/MorphoCloud/MorphoCloudInstances) will not be accessible. All existing instances and volumes will be deleted. If you still have an open issue and a shelved instance, make sure to download any important files — you will not be able to recover them afterward. Throughout June we will do the migration and testing, and by **July 1st** (or possibly earlier) the new system will be functional.

**What stays the same**

The functionality and how you interact with the system will remain the same.

**What changes**

The major difference is that users will now onboard themselves with the MorphoCloud GitHub organization using their ORCID login and fill in their personal information. This is a one-time procedure. After that, you will receive an invitation to become a member of the MorphoCloud Organization. Once a member, you no longer need to identify yourself or your use case — the only information visible to other users will be your GitHub handle. More importantly, as a member of the org, you are already granted approval to use the system, so you can create and manage your instance right away.

**Additional benefits**
- Automated notifications of planned JS2 outages
- Meaningful error messages if failure is due to lack of resource availability at JS2
- Support by tagging us (@morphocloud-admins) on the issues page
- A new GPU instance type to mitigate the chronic lack of `g3.xl` availability
- A registered domain, **morphocloud.org** — all platform emails will now come from this domain, which should mitigate some emails going to spam folders or being blocked by university IT filters

**Next steps**

In about a month, a follow-up announcement will provide instructions for onboarding via ORCID. The SlicerMorph/MorphoCloud joint mailing list (1–3 posts a month) will also be used to share notifications about upcoming workshops, office hours, and project updates.
